name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: geese-crossing/package.json

      - name: Install dependencies
        working-directory: geese-crossing
        run: npm ci

      - name: Build and export
        working-directory: geese-crossing
        env:
          NEXT_BASE_PATH: /${{ github.event.repository.name }}
          NEXT_ASSET_PREFIX: /${{ github.event.repository.name }}
          NEXT_PUBLIC_BASE_PATH: /${{ github.event.repository.name }}
        run: |
          npm run preexport
          npm run export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: geese-crossing/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
